[project]
name = "ollama-proxy"
version = "0.1.0"
description = "A Flask-based proxy for logging and modifying requests to an Ollama server."
readme = "README.md"
# authors = ["michael-heinrich", "gmacario <your-email@example.com>"]
license = "MIT"
requires-python = ">=3.11"

dependencies = [
    "flask",
    "icecream",
    "python-dotenv",
    "requests",
]

# EOF
